
[frontMatter]                                                                 
description = "Catalyst ports your iPad apps over to macOS. This guide contains a ton of tips and tricks to help you succeed in adding Catalyst support to your app"
title = "Ultimate Catalyst Guide"   
created = "2019-07-06" 
published = true                                                                                               
keywords = ["catalyst", "macos", "uikitformac"]
tags = ["catalyst", "macos", "uikitformac"]
  
[meta]          
featured = "true"
swift_version = "5.1"
short_title = "ðŸ–¥ Ultimate Catalyst Guide"
short_code = "<pre class='Swift'><code><span class='apvsource swift'>#if<span class='apvkeyword apvoperator apvcustom apvpostfix apvunary swift'> targetEnvironment(</span>UIKitForMac</span><span class='apvkeyword apvoperator apvcustom apvpostfix apvunary swift'>)</span></code></pre>"
feature_image = "/img-content/catalyst/feature_image.jpg"
---
- [Intro](intro.md)
  - [Features](features.md)
  - [App Lifecycle](how/app_lifecycle.md)
- [First Steps](firststeps/intro.md)
  - [Signing](firststeps/signing.md)
  - [Conditional Compilation](firststeps/conditional_compilation.md)
  - [A SceneDelegate](firststeps/scene_delegate.md)
  - [Multiple Windows](firststeps/multiple_windows.md)
  - [A Bridging Header](firststeps/bridgingheader.md)
  - [The Toolbar](firststeps/toolbar.md)
  - [The Sidebar](firststeps/sidebar.md)
  - [The Menubar](firststeps/modify_menubar.md)
  - [The Touchbar](firststeps/touchbar.md)
  - [Context Menus](firststeps/context_menus.md)
  - [Keyboard Shortcuts](firststeps/keyboard_shortcuts.md)
  - [Preferences](firststeps/preferences.md)
  - [Third Party SDKs](firststeps/sdks.md)
  - [Notable Differences](firststeps/issues.md)
  - [Coding Best Practices](firststeps/best_practices_code.md)
  - [Design Best Practices](firststeps/best_practices_design.md)
- [How Do I...](how/intro.md)
  - [Add a New Window entry](how/custom_new_window_entry.md)
  - [Add a Segmented Control to the ToolBar?](how/segmented_control_toolbar.md)
  - [Hide the iOS TabBar?](how/hide_tabbar_with_toolbar.md)
  - [Modify the Window?](how/modify_window.md)
  - [Use HIG TouchBar images?](how/touchbar_images.md)
  - [Dynamically update the TouchBar?](how/dynamically_update_touchbar.md)
  - [Nest multiple TouchBars?](how/nest_touchbars.md)
  - [Implement Drag and Drop?](how/drag_and_drop.md)
  - [Create Export / Import file Dialogs?](how/open_save_export_import.md)
  - [Configure the macOS Sandbox?](how/sandbox.md)
  - [Support Dark Mode?](how/darkmode.md)
  - [Support multiple Different Windows?](how/multiple_different_windows.md)
  - [Support Mouse Hovering?](how/mouse_hovering.md)
  - [Write code that only runs on macOS?](how/conditional_code.md)
  - [Implement Complex Preferences?](how/logic_preferences.md)
  - [Support macOS Icons?](how/dark_mode_icons.md)
  - [Use Share Extensions](how/share_extensions.md)
  - [Conditionally Enable MenuBar items?](how/enable_disable_menubar_items.md)
  - [Conditionally Enable ToolBar items?](how/enable_disable_toolbar_items.md)
  - [Conditionally Enable TouchBar?](how/enable_disable_touchbar_items.md)
  - [Use the Responder Chain?](how/responder_chain.md)
  - [Prevent Piracy](piracy.md)
- [Known Issues?](issues/issues.md)
