[Project]
keywords = ["swift", "rust", "about", "blog", "diary"]

[Folders]
# The file and folders that should be copied over from within the public folder
publicCopyFolders = ["css", "img", "js", "content"]
booksFolder = "guides"
booksFolderName = "guides"
categoryFolderName = "topics"
books = [
  "pattern_matching/summary.toml", 
  "advanced_practical_enum_examples/summary.toml", 
  "map_flatmap_reduce_more/summary.toml", 
  "associated_types/summary.toml", 
  "tuples/summary.toml",
  "optionals/summary.toml", 
  "swift_reflection/summary.toml",
]

# [RSS]
# title = "Benedikt Terhechte"
# absoluteFeedAddress = "https://terhech.de/feed.rss"
