[Project]
baseURL = "https://appventure.me"
keywords = ["swift", "objective-c", "ios", "macos", "tvos", "watch", "xcode", "iphone", "linux", "open source"]
postsPerIndex = 20
renderOnePageBooks = true
codeClassPrefix = "apv"

[Folders]
# The file and folders that should be copied over from within the public folder
publicCopyFolders = ["css", "img", "js", "content", "img-content"]
booksFolder = "guides"
booksFolderName = "guides"
categoryFolderName = "topics"
books = [
  "pattern_matching/summary.toml", 
  "advanced_practical_enum_examples/summary.toml", 
  "map_flatmap_reduce_more/summary.toml", 
  "associated_types/summary.toml", 
  "tuples/summary.toml",
  "optionals/summary.toml", 
  "swift_reflection/summary.toml",
]

[Shortlinks]
switch = "/guides/pattern_matching/intro.html"
enum-custom-data-types = "/guides/advanced_practical_enum_examples/advanced_enum_usage/custom_data_types.html"
failable-initializer = "https://docs.swift.org/swift-book/LanguageGuide/Initialization.html"
type-erase = "/guides/associated_types/type_erasure/intro.html"
optional = "/guides/optionals/intro.html"
tuple = "/guides/tuples/introduction.html"
map-filter-reduce = "/guides/map_flatmap_reduce_more/intro.html"
reflection = "/guides/swift_reflection/introduction.html"
match-operator = "/guides/pattern_matching/advanced_pattern_matching/expressionpattern.html"
enum = "/guides/advanced_practical_enum_examples/introduction.html"

[RSS]
title = "AppVenture. Simple Swift Guides"
feedAddress = "feed.rss"
authorEmail = "benedikt.terhechte@appventure.me"
authorName = "Benedikt Terhechte"
description = "AppVenture provides simple swift guides to help you along your Swift journey."
