[frontMatter]
title = "Optionals"
keywords = ["feature", "lisp", "swift", "optional", "scala", "simple", "optionals", "switch", "chaining", "for", "pattern", "matching", "clojure", "haskell"]
tags = ["swift", "ios", "cocoa"]
created = "2015-08-20"
description = "Best practices for handling Swift's `Optional` and extending them to make them much more approachable"
published = true

[meta]
swift_version = "5.1"
short_title = "⁉️ Optionals"
short_code = "<pre class='Swift'><code><span class='apvsource swift'>a?<span class='apvkeyword apvoperator apvcustom apvpostfix apvunary swift'>.</span>b?<span class='apvkeyword apvoperator apvcustom apvpostfix apvunary swift'>.</span>c? <span class='apvkeyword apvoperator apvcomparative swift'>==</span> <span class='apvconstant apvnil swift'>nil</span> </span></code></pre></code></pre>"
---
- [What are Optionals](intro.md)
- [Why Optionals are useful](why_optionals_are_useful.md)
- [How to handle optionals](how_to_handle_optionals.md)
- [Advanced Optionals](advanced_optionals.md)
- [Extending Optionals](extending_optionals.md)