[frontMatter]
description = "Understand how to model your way around some of the issues that arise when introducing associated types into your protocols"
title = "Patterns for Working With Associated Types"
created = "2017-12-10"
keywords = ["swift", "protocol", "protocols", "associated", "associatedtype", "typealias", "pattern", "pat"]
slug = "2017-12-10-patterns-for-working-with-associated-types.html"
tags = []
published = true

[meta]
featured = "true"
swift_version = "5.1"
short_title = "üßôüèª Associated Types"
short_code = "<pre class='Swift'><code><span class='source swift'><span class='apvstorage apvtype swift'>protocol</span> Host {<br/> associatedType Client<br/>} </span></code></pre></code></pre>"
---
- [Associated Types](associated_types.md)
- [Associated Types Trouble](associated_types_trouble.md)
- [Equatable](working_around_associated_type_issues/equatable.md)
  - [Associated Types and Self](working_around_associated_type_issues/self.md)
  - [Method-Only Types](working_around_associated_type_issues/method_only_types.md)
  - [Hiding Behind Protocols](working_around_associated_type_issues/hiding_behind_protocols.md)
- [Type Erasure](type_erasure/intro.md)
  - [An Abstract Class](type_erasure/an_abstract_class.md)
  - [A Box Type](type_erasure/a_box_type.md)
  - [Puttting it all together](type_erasure/putting_it_all_together.md)
- [Conclusion](conclusion.md)
